// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMedia.Infrastructure;

#nullable disable

namespace SocialMedia.Infrastructure.Migrations
{
    [DbContext(typeof(SocialMediaDbContext))]
    [Migration("20260524171301_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocialMedia.Domain.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Nonce")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("SocialMedia.Domain.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SocialMedia.Domain.CommentReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorProfilePicUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("CommentReads", (string)null);
                });

            modelBuilder.Entity("SocialMedia.Domain.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("SocialMedia.Domain.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SocialMedia.Domain.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("SocialMedia.Domain.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("SocialMedia.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SocialMedia.Domain.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("LastRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("OutboxEvents");
                });

            modelBuilder.Entity("SocialMedia.Domain.Poll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("SocialMedia.Domain.PollOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("PollOptions");
                });

            modelBuilder.Entity("SocialMedia.Domain.PollVoteRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PollId", "UserId")
                        .IsUnique();

                    b.ToTable("PollVoteRecords");
                });

            modelBuilder.Entity("SocialMedia.Domain.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("StatusFullScreen")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SocialMedia.Domain.PostReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorProfilePicUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("RankUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReactionCount")
                        .HasColumnType("int");

                    b.Property<bool>("StatusFullScreen")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TrendingScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CommentCount")
                        .HasDatabaseName("IX_Posts_CommentCount");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Posts_CreatedAt");

                    b.HasIndex("GroupId");

                    b.HasIndex("ReactionCount")
                        .HasDatabaseName("IX_Posts_ReactionCount");

                    b.HasIndex("TrendingScore", "CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Posts_RankScore_CreatedAt");

                    b.ToTable("PostReads", (string)null);
                });

            modelBuilder.Entity("SocialMedia.Domain.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SocialMedia.Domain.StatsRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveUsers")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NewPosts")
                        .HasColumnType("int");

                    b.Property<int>("ResultingComments")
                        .HasColumnType("int");

                    b.Property<int>("ResultingReactions")
                        .HasColumnType("int");

                    b.Property<int>("StatsType")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalPosts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StatsRecords");
                });

            modelBuilder.Entity("SocialMedia.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ThemeJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("SocialMedia.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastActiveAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SocialMedia.Domain.UserActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("SocialMedia.Domain.UserBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlockedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BlockedUserId");

                    b.HasIndex("BlockerId");

                    b.ToTable("UserBlocks");
                });

            modelBuilder.Entity("SocialMedia.Domain.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PollOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PollOptionId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("SocialMedia.Domain.Comment", b =>
                {
                    b.HasOne("SocialMedia.Domain.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("SocialMedia.Domain.TagDto", "AdminTags", b1 =>
                        {
                            b1.Property<Guid>("CommentId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.Property<string>("Topic")
                                .IsRequired();

                            b1.HasKey("CommentId", "__synthesizedOrdinal");

                            b1.ToTable("Comments");

                            b1
                                .ToJson("AdminTags")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CommentId");
                        });

                    b.OwnsMany("SocialMedia.Domain.MediaDto", "Media", b1 =>
                        {
                            b1.Property<Guid>("CommentId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("CommentId", "__synthesizedOrdinal");

                            b1.ToTable("Comments");

                            b1
                                .ToJson("Media")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CommentId");
                        });

                    b.OwnsMany("SocialMedia.Domain.TagDto", "Tags", b1 =>
                        {
                            b1.Property<Guid>("CommentId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.Property<string>("Topic")
                                .IsRequired();

                            b1.HasKey("CommentId", "__synthesizedOrdinal");

                            b1.ToTable("Comments");

                            b1
                                .ToJson("Tags")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CommentId");
                        });

                    b.Navigation("AdminTags");

                    b.Navigation("Media");

                    b.Navigation("Post");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("SocialMedia.Domain.CommentReadModel", b =>
                {
                    b.OwnsMany("SocialMedia.Domain.TagDto", "AdminTags", b1 =>
                        {
                            b1.Property<Guid>("CommentReadModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.Property<string>("Topic")
                                .IsRequired();

                            b1.HasKey("CommentReadModelId", "__synthesizedOrdinal");

                            b1.ToTable("CommentReads");

                            b1
                                .ToJson("AdminTags")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CommentReadModelId");
                        });

                    b.OwnsMany("SocialMedia.Domain.MediaDto", "Media", b1 =>
                        {
                            b1.Property<Guid>("CommentReadModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("CommentReadModelId", "__synthesizedOrdinal");

                            b1.ToTable("CommentReads");

                            b1
                                .ToJson("Media")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CommentReadModelId");
                        });

                    b.OwnsMany("SocialMedia.Domain.ReactionReadDto", "Reactions", b1 =>
                        {
                            b1.Property<Guid>("CommentReadModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("Count");

                            b1.Property<string>("Emoji")
                                .IsRequired();

                            b1.HasKey("CommentReadModelId", "__synthesizedOrdinal");

                            b1.ToTable("CommentReads");

                            b1
                                .ToJson("Reactions")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CommentReadModelId");
                        });

                    b.OwnsMany("SocialMedia.Domain.TagDto", "Tags", b1 =>
                        {
                            b1.Property<Guid>("CommentReadModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.Property<string>("Topic")
                                .IsRequired();

                            b1.HasKey("CommentReadModelId", "__synthesizedOrdinal");

                            b1.ToTable("CommentReads");

                            b1
                                .ToJson("Tags")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CommentReadModelId");
                        });

                    b.OwnsOne("SocialMedia.Domain.CommentStatsDto", "Stats", b1 =>
                        {
                            b1.Property<Guid>("CommentReadModelId");

                            b1.Property<int>("LikeCount");

                            b1.HasKey("CommentReadModelId");

                            b1.ToTable("CommentReads");

                            b1
                                .ToJson("Stats")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CommentReadModelId");
                        });

                    b.Navigation("AdminTags");

                    b.Navigation("Media");

                    b.Navigation("Reactions");

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("SocialMedia.Domain.Feedback", b =>
                {
                    b.HasOne("SocialMedia.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Domain.GroupMember", b =>
                {
                    b.HasOne("SocialMedia.Domain.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Domain.Like", b =>
                {
                    b.HasOne("SocialMedia.Domain.Comment", "Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId");

                    b.HasOne("SocialMedia.Domain.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId");

                    b.Navigation("Comment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMedia.Domain.Notification", b =>
                {
                    b.HasOne("SocialMedia.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Domain.Poll", b =>
                {
                    b.HasOne("SocialMedia.Domain.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SocialMedia.Domain.PollOption", b =>
                {
                    b.HasOne("SocialMedia.Domain.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("SocialMedia.Domain.Post", b =>
                {
                    b.HasOne("SocialMedia.Domain.Group", "Group")
                        .WithMany("Posts")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("SocialMedia.Domain.TagDto", "AdminTags", b1 =>
                        {
                            b1.Property<Guid>("PostId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.Property<string>("Topic")
                                .IsRequired();

                            b1.HasKey("PostId", "__synthesizedOrdinal");

                            b1.ToTable("Posts");

                            b1
                                .ToJson("AdminTags")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.OwnsMany("SocialMedia.Domain.MediaDto", "Media", b1 =>
                        {
                            b1.Property<Guid>("PostId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("PostId", "__synthesizedOrdinal");

                            b1.ToTable("Posts");

                            b1
                                .ToJson("Media")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.OwnsMany("SocialMedia.Domain.TagDto", "Tags", b1 =>
                        {
                            b1.Property<Guid>("PostId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.Property<string>("Topic")
                                .IsRequired();

                            b1.HasKey("PostId", "__synthesizedOrdinal");

                            b1.ToTable("Posts");

                            b1
                                .ToJson("Tags")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.Navigation("AdminTags");

                    b.Navigation("Group");

                    b.Navigation("Media");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("SocialMedia.Domain.PostReadModel", b =>
                {
                    b.OwnsMany("SocialMedia.Domain.CommentReadDto", "TopComments", b1 =>
                        {
                            b1.Property<Guid>("PostReadModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<Guid>("AuthorId");

                            b1.Property<string>("AuthorName")
                                .IsRequired();

                            b1.Property<string>("AuthorProfilePicUrl");

                            b1.Property<Guid>("CommentId");

                            b1.Property<string>("Content")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<string>("CreatedBy");

                            b1.Property<int>("LikeCount");

                            b1.Property<Guid>("TenantId");

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1.Property<string>("UserReaction");

                            b1.HasKey("PostReadModelId", "__synthesizedOrdinal");

                            b1.ToTable("PostReads");

                            b1
                                .ToJson("TopComments")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PostReadModelId");

                            b1.OwnsMany("SocialMedia.Domain.TagDto", "AdminTags", b2 =>
                                {
                                    b2.Property<Guid>("CommentReadDtoPostReadModelId");

                                    b2.Property<int>("CommentReadDto__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Text")
                                        .IsRequired();

                                    b2.Property<string>("Topic")
                                        .IsRequired();

                                    b2.HasKey("CommentReadDtoPostReadModelId", "CommentReadDto__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("PostReads");

                                    b2.WithOwner()
                                        .HasForeignKey("CommentReadDtoPostReadModelId", "CommentReadDto__synthesizedOrdinal");
                                });

                            b1.OwnsMany("SocialMedia.Domain.MediaDto", "Media", b2 =>
                                {
                                    b2.Property<Guid>("CommentReadDtoPostReadModelId");

                                    b2.Property<int>("CommentReadDto__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Url")
                                        .IsRequired();

                                    b2.HasKey("CommentReadDtoPostReadModelId", "CommentReadDto__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("PostReads");

                                    b2.WithOwner()
                                        .HasForeignKey("CommentReadDtoPostReadModelId", "CommentReadDto__synthesizedOrdinal");
                                });

                            b1.OwnsMany("SocialMedia.Domain.ReactionReadDto", "Reactions", b2 =>
                                {
                                    b2.Property<Guid>("CommentReadDtoPostReadModelId");

                                    b2.Property<int>("CommentReadDto__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<int>("Count");

                                    b2.Property<string>("Emoji")
                                        .IsRequired();

                                    b2.HasKey("CommentReadDtoPostReadModelId", "CommentReadDto__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("PostReads");

                                    b2.WithOwner()
                                        .HasForeignKey("CommentReadDtoPostReadModelId", "CommentReadDto__synthesizedOrdinal");
                                });

                            b1.OwnsMany("SocialMedia.Domain.TagDto", "Tags", b2 =>
                                {
                                    b2.Property<Guid>("CommentReadDtoPostReadModelId");

                                    b2.Property<int>("CommentReadDto__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Text")
                                        .IsRequired();

                                    b2.Property<string>("Topic")
                                        .IsRequired();

                                    b2.HasKey("CommentReadDtoPostReadModelId", "CommentReadDto__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("PostReads");

                                    b2.WithOwner()
                                        .HasForeignKey("CommentReadDtoPostReadModelId", "CommentReadDto__synthesizedOrdinal");
                                });

                            b1.Navigation("AdminTags");

                            b1.Navigation("Media");

                            b1.Navigation("Reactions");

                            b1.Navigation("Tags");
                        });

                    b.OwnsMany("SocialMedia.Domain.TagDto", "AdminTags", b1 =>
                        {
                            b1.Property<Guid>("PostReadModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.Property<string>("Topic")
                                .IsRequired();

                            b1.HasKey("PostReadModelId", "__synthesizedOrdinal");

                            b1.ToTable("PostReads");

                            b1
                                .ToJson("AdminTags")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PostReadModelId");
                        });

                    b.OwnsMany("SocialMedia.Domain.MediaDto", "Media", b1 =>
                        {
                            b1.Property<Guid>("PostReadModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("PostReadModelId", "__synthesizedOrdinal");

                            b1.ToTable("PostReads");

                            b1
                                .ToJson("Media")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PostReadModelId");
                        });

                    b.OwnsMany("SocialMedia.Domain.ReactionReadDto", "Reactions", b1 =>
                        {
                            b1.Property<Guid>("PostReadModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("Count");

                            b1.Property<string>("Emoji")
                                .IsRequired();

                            b1.HasKey("PostReadModelId", "__synthesizedOrdinal");

                            b1.ToTable("PostReads");

                            b1
                                .ToJson("Reactions")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PostReadModelId");
                        });

                    b.OwnsMany("SocialMedia.Domain.TagDto", "Tags", b1 =>
                        {
                            b1.Property<Guid>("PostReadModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.Property<string>("Topic")
                                .IsRequired();

                            b1.HasKey("PostReadModelId", "__synthesizedOrdinal");

                            b1.ToTable("PostReads");

                            b1
                                .ToJson("Tags")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PostReadModelId");
                        });

                    b.Navigation("AdminTags");

                    b.Navigation("Media");

                    b.Navigation("Reactions");

                    b.Navigation("Tags");

                    b.Navigation("TopComments");
                });

            modelBuilder.Entity("SocialMedia.Domain.Report", b =>
                {
                    b.HasOne("SocialMedia.Domain.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SocialMedia.Domain.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Comment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMedia.Domain.StatsRecord", b =>
                {
                    b.OwnsMany("SocialMedia.Domain.ReactionStat", "ReactionBreakdown", b1 =>
                        {
                            b1.Property<Guid>("StatsRecordId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("Count");

                            b1.Property<string>("Emoji")
                                .IsRequired();

                            b1.HasKey("StatsRecordId", "__synthesizedOrdinal");

                            b1.ToTable("StatsRecords");

                            b1
                                .ToJson("ReactionBreakdown")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("StatsRecordId");
                        });

                    b.Navigation("ReactionBreakdown");
                });

            modelBuilder.Entity("SocialMedia.Domain.UserActivity", b =>
                {
                    b.OwnsMany("SocialMedia.Domain.UserReactionActivity", "Reactions", b1 =>
                        {
                            b1.Property<Guid>("UserActivityId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Emoji")
                                .IsRequired();

                            b1.Property<Guid>("EntityId");

                            b1.Property<string>("EntityType")
                                .IsRequired();

                            b1.HasKey("UserActivityId", "__synthesizedOrdinal");

                            b1.ToTable("UserActivities");

                            b1
                                .ToJson("Reactions")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("UserActivityId");
                        });

                    b.OwnsMany("SocialMedia.Domain.UserVoteActivity", "Votes", b1 =>
                        {
                            b1.Property<Guid>("UserActivityId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<Guid>("OptionId");

                            b1.Property<Guid>("PollId");

                            b1.Property<DateTimeOffset>("VotedAt");

                            b1.HasKey("UserActivityId", "__synthesizedOrdinal");

                            b1.ToTable("UserActivities");

                            b1
                                .ToJson("Votes")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("UserActivityId");
                        });

                    b.Navigation("Reactions");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("SocialMedia.Domain.UserBlock", b =>
                {
                    b.HasOne("SocialMedia.Domain.User", "BlockedUser")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialMedia.Domain.User", "Blocker")
                        .WithMany()
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlockedUser");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("SocialMedia.Domain.Vote", b =>
                {
                    b.HasOne("SocialMedia.Domain.PollOption", "PollOption")
                        .WithMany("Votes")
                        .HasForeignKey("PollOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PollOption");
                });

            modelBuilder.Entity("SocialMedia.Domain.Comment", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("SocialMedia.Domain.Group", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SocialMedia.Domain.Poll", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("SocialMedia.Domain.PollOption", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("SocialMedia.Domain.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
