// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMedia.Infrastructure;

#nullable disable

namespace SocialMedia.Infrastructure.Migrations
{
    [DbContext(typeof(SocialMediaReadDbContext))]
    partial class SocialMediaReadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocialMedia.Domain.CommentReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorProfilePicUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CommentReads", (string)null);
                });

            modelBuilder.Entity("SocialMedia.Domain.PostReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("StatusFullScreen")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostReads", (string)null);
                });

            modelBuilder.Entity("SocialMedia.Domain.CommentReadModel", b =>
                {
                    b.OwnsMany("SocialMedia.Domain.TagDto", "AdminTags", b1 =>
                        {
                            b1.Property<Guid>("CommentReadModelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Topic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CommentReadModelId", "Id");

                            b1.ToTable("CommentReads");

                            b1.ToJson("AdminTags");

                            b1.WithOwner()
                                .HasForeignKey("CommentReadModelId");
                        });

                    b.OwnsMany("SocialMedia.Domain.ReactionReadDto", "Reactions", b1 =>
                        {
                            b1.Property<Guid>("CommentReadModelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("Count")
                                .HasColumnType("int");

                            b1.Property<string>("Emoji")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CommentReadModelId", "Id");

                            b1.ToTable("CommentReads");

                            b1.ToJson("Reactions");

                            b1.WithOwner()
                                .HasForeignKey("CommentReadModelId");
                        });

                    b.OwnsMany("SocialMedia.Domain.TagDto", "Tags", b1 =>
                        {
                            b1.Property<Guid>("CommentReadModelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Topic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CommentReadModelId", "Id");

                            b1.ToTable("CommentReads");

                            b1.ToJson("Tags");

                            b1.WithOwner()
                                .HasForeignKey("CommentReadModelId");
                        });

                    b.OwnsOne("SocialMedia.Domain.CommentStatsDto", "Stats", b1 =>
                        {
                            b1.Property<Guid>("CommentReadModelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("LikeCount")
                                .HasColumnType("int");

                            b1.HasKey("CommentReadModelId");

                            b1.ToTable("CommentReads");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("CommentReadModelId");
                        });

                    b.Navigation("AdminTags");

                    b.Navigation("Reactions");

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("SocialMedia.Domain.PostReadModel", b =>
                {
                    b.OwnsMany("SocialMedia.Domain.CommentReadDto", "TopComments", b1 =>
                        {
                            b1.Property<Guid>("PostReadModelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AuthorName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AuthorProfilePicUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("CommentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int>("LikeCount")
                                .HasColumnType("int");

                            b1.HasKey("PostReadModelId", "Id");

                            b1.ToTable("PostReads");

                            b1.ToJson("TopComments");

                            b1.WithOwner()
                                .HasForeignKey("PostReadModelId");

                            b1.OwnsMany("SocialMedia.Domain.TagDto", "AdminTags", b2 =>
                                {
                                    b2.Property<Guid>("CommentReadDtoPostReadModelId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("CommentReadDtoId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Topic")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("CommentReadDtoPostReadModelId", "CommentReadDtoId", "Id");

                                    b2.ToTable("PostReads");

                                    b2.WithOwner()
                                        .HasForeignKey("CommentReadDtoPostReadModelId", "CommentReadDtoId");
                                });

                            b1.OwnsMany("SocialMedia.Domain.ReactionReadDto", "Reactions", b2 =>
                                {
                                    b2.Property<Guid>("CommentReadDtoPostReadModelId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("CommentReadDtoId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    b2.Property<int>("Count")
                                        .HasColumnType("int");

                                    b2.Property<string>("Emoji")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("CommentReadDtoPostReadModelId", "CommentReadDtoId", "Id");

                                    b2.ToTable("PostReads");

                                    b2.WithOwner()
                                        .HasForeignKey("CommentReadDtoPostReadModelId", "CommentReadDtoId");
                                });

                            b1.OwnsMany("SocialMedia.Domain.TagDto", "Tags", b2 =>
                                {
                                    b2.Property<Guid>("CommentReadDtoPostReadModelId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("CommentReadDtoId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Topic")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("CommentReadDtoPostReadModelId", "CommentReadDtoId", "Id");

                                    b2.ToTable("PostReads");

                                    b2.WithOwner()
                                        .HasForeignKey("CommentReadDtoPostReadModelId", "CommentReadDtoId");
                                });

                            b1.Navigation("AdminTags");

                            b1.Navigation("Reactions");

                            b1.Navigation("Tags");
                        });

                    b.OwnsMany("SocialMedia.Domain.TagDto", "AdminTags", b1 =>
                        {
                            b1.Property<Guid>("PostReadModelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Topic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PostReadModelId", "Id");

                            b1.ToTable("PostReads");

                            b1.ToJson("AdminTags");

                            b1.WithOwner()
                                .HasForeignKey("PostReadModelId");
                        });

                    b.OwnsMany("SocialMedia.Domain.ReactionReadDto", "Reactions", b1 =>
                        {
                            b1.Property<Guid>("PostReadModelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("Count")
                                .HasColumnType("int");

                            b1.Property<string>("Emoji")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PostReadModelId", "Id");

                            b1.ToTable("PostReads");

                            b1.ToJson("Reactions");

                            b1.WithOwner()
                                .HasForeignKey("PostReadModelId");
                        });

                    b.OwnsMany("SocialMedia.Domain.TagDto", "Tags", b1 =>
                        {
                            b1.Property<Guid>("PostReadModelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Topic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PostReadModelId", "Id");

                            b1.ToTable("PostReads");

                            b1.ToJson("Tags");

                            b1.WithOwner()
                                .HasForeignKey("PostReadModelId");
                        });

                    b.OwnsOne("SocialMedia.Domain.PostStatsDto", "Stats", b1 =>
                        {
                            b1.Property<Guid>("PostReadModelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CommentCount")
                                .HasColumnType("int");

                            b1.Property<int>("LikeCount")
                                .HasColumnType("int");

                            b1.Property<int>("TrendingScore")
                                .HasColumnType("int");

                            b1.HasKey("PostReadModelId");

                            b1.ToTable("PostReads");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("PostReadModelId");
                        });

                    b.Navigation("AdminTags");

                    b.Navigation("Reactions");

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Tags");

                    b.Navigation("TopComments");
                });
#pragma warning restore 612, 618
        }
    }
}
