@startuml
participant User

User -> API: Add User to Group
activate API #FFBBBB

API -> API: Save linking of User to Group to UserDetails table
activate API #DarkSalmon

deactivate API
API -> User: Done
deactivate API
@enduml
